name: API Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Allow manual trigger
  workflow_dispatch:

# Environment variables
env:
  BASE_URL: 'https://macthify-be.vercel.app/v1/api'
  NODE_VERSION: '22'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    # Configure timeout to prevent long-running tests
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Initialize npm project
        run: |
          npm init -y
          npm install newman newman-reporter-htmlextra newman-reporter-allure allure-commandline --save-dev
          npm install -g newman newman-reporter-htmlextra newman-reporter-allure allure-commandline

      - name: Create Results Directory
        run: |
          mkdir -p test-results/newman
          mkdir -p test-results/allure-results

      - name: Update Environment File
        run: |
          echo '{
            "id": "env-id",
            "name": "CI Environment",
            "values": [
              {
                "key": "base_url",
                "value": "${{ env.BASE_URL }}",
                "enabled": true
              }
            ]
          }' > environment.json

      - name: Run Profile API Tests
        continue-on-error: false
        run: |
          newman run Profile.postman_collection.json \
            -e environment.json \
            --folder "TESTS/POSITIVE TESTS" \
            --folder "TESTS/NEGATIVE TESTS" \
            --reporters cli,htmlextra,allure \
            --reporter-htmlextra-export test-results/newman/profile-tests.html \
            --reporter-allure-export test-results/allure-results

      - name: Run Auth API Tests
        continue-on-error: false
        run: |
          newman run AUTH.postman_collection.json \
            -e environment.json \
            --reporters cli,htmlextra,allure \
            --reporter-htmlextra-export test-results/newman/auth-tests.html \
            --reporter-allure-export test-results/allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate test-results/allure-results --clean -o test-results/allure-report

      - name: Upload Newman HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: test-results/newman/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-results/allure-report/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./test-results/allure-report
