name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install Newman and HTML reporter
      - name: Install dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run Profile API Test and export updated environment
      - name: Run Profile API Tests (Generate Variables)
        run: |
          newman run Profile.postman_collection.json \
            -e DEV.postman_environment.json \  # Use static environment
            -r cli,htmlextra \
            --reporter-htmlextra-export profile-test-report.html \
            --export-environment updated-env.json  # Export dynamic vars

      # Run Auth API Test using updated environment
      - name: Run Auth API Tests (Reuse Variables)
        run: |
          newman run AUTH.postman_collection.json \
            -e updated-env.json \  # Use updated environment
            -r cli,htmlextra \
            --reporter-htmlextra-export auth-test-report.html

      # Upload Test Reports for debugging
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: api-test-reports
          path: |
            profile-test-report.html
            auth-test-report.html

      # Upload Updated Environment for debugging (optional)
      - name: Upload Updated Environment (Debug)
        uses: actions/upload-artifact@v3
        with:
          name: updated-environment
          path: updated-env.json
