name: API Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_URL: 'https://macthify-be.vercel.app/v1/api'

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and Reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure

      - name: Update Environment File
        run: |
          jq '.values += [{"key": "base_url", "value": "${{ env.BASE_URL }}", "type": "string", "enabled": true}]' DEV.postman_environment.json > updated_env.json

      - name: Run Profile API tests
        run: |
          newman run Profile.postman_collection.json \
            -e updated_env.json \
            --folder "TESTS/POSITIVE TESTS" \
            --folder "TESTS/NEGATIVE TESTS" \
            -r cli,htmlextra \
            --reporter-htmlextra-export profile-test-report.html
            
      - name: Run AUTH API tests
        run: |
          newman run AUTH.postman_collection.json \
            -e updated_env.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export auth-test-report.html

      - name: Upload Profile test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: profile-api-test-report
          path: profile-test-report.html

      - name: Upload AUTH test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: auth-api-test-report
          path: auth-test-report.html

  deploy-report:
    needs: run-api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Profile test report artifact
        uses: actions/download-artifact@v3
        with:
          name: profile-api-test-report

      - name: Download AUTH test report artifact
        uses: actions/download-artifact@v3
        with:
          name: auth-api-test-report

      - name: Create report directory
        run: |
          mkdir -p reports
          mv profile-test-report.html reports/
          mv auth-test-report.html reports/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
