name: Matchify API Tests
on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
permissions:
 issues: write
 contents: write
jobs:
 test:
   runs-on: ubuntu-22.04
   steps:
     - uses: actions/checkout@v3
     
     - name: Install Newman
       run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         npm install -g newman-reporter-allure
         npm install -g allure-commandline

     - name: Create Results Directory
       run: mkdir -p test-results/allure-results

     - name: Update Environment File
       run: |
         jq '.values[] |= if .key == "base_url" then .value = "${{ secrets.API_BASE_URL }}" else . end' ./DEV.postman_environment.json > tmp.json && mv tmp.json ./DEV.postman_environment.json

     - name: Run Profile Tests
       run: |
         newman run Profile.postman_collection.json \
         -e ./DEV.postman_environment.json \
         --folder "TESTS/POSITIVE TESTS" \
         --folder "TESTS/NEGATIVE TESTS" \
         --reporters cli,htmlextra \
         --reporter-htmlextra-export test-results/profile-report.html \
         --export-environment ./updated-env.json

     - name: Run Auth Tests
       run: |
         newman run AUTH.postman_collection.json \
         -e ./updated-env.json \
         --reporters cli,htmlextra \
         --reporter-htmlextra-export test-results/login-report.html

     - name: Generate Allure Report
       if: always()
       run: |
         allure generate test-results/allure-results --clean -o test-results/allure-report || true

     - name: Upload Test Results
       if: always()
       uses: actions/upload-artifact@v3
       with:
         name: test-reports
         path: test-results/

     - name: Deploy Reports to GitHub Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: ./test-results/allure-report

     - name: Notify on Failure
       if: failure()
       uses: actions/github-script@v6
       with:
         script: |
           github.rest.issues.create({
             owner: context.repo.owner,
             repo: context.repo.repo,
             title: 'API Tests Failed',
             body: 'API tests failed in workflow. Check the action logs for details.'
           })
