name: API Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create Profile Postman collection
        run: |
          echo '{
            "info": {
              "name": "Profile API Test",
              "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "item": [
              {
                "name": "Create Profile Test",
                "request": {
                  "method": "POST",
                  "header": [
                    { "key": "Content-Type", "value": "application/json" }
                  ],
                  "url": "https://macthify-be.vercel.app/v1/api/create-profile",
                  "body": {
                    "mode": "raw",
                    "raw": "{\"username\": \"testuser\", \"bio\": \"This is a test bio.\"}"
                  }
                },
                "response": []
              }
            ]
          }' > profile_collection.json

      - name: Create AUTH Postman collection
        run: |
          echo '{
            "info": {
              "name": "Auth API Test",
              "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "item": [
              {
                "name": "Login Test",
                "request": {
                  "method": "POST",
                  "header": [
                    { "key": "Content-Type", "value": "application/json" }
                  ],
                  "url": "https://macthify-be.vercel.app/v1/api/auth/login",
                  "body": {
                    "mode": "raw",
                    "raw": "{\"email\": \"test@example.com\", \"password\": \"password123\"}"
                  }
                },
                "response": []
              }
            ]
          }' > auth_collection.json

      - name: Run Profile API tests with Newman
        run: |
          newman run profile_collection.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export profile-test-report.html

      - name: Run AUTH API tests with Newman
        run: |
          newman run auth_collection.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export auth-test-report.html

      - name: Upload Profile test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: profile-api-test-report
          path: profile-test-report.html

      - name: Upload AUTH test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: auth-api-test-report
          path: auth-test-report.html

  deploy-report:
    needs: run-api-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Profile test report artifact
        uses: actions/download-artifact@v3
        with:
          name: profile-api-test-report

      - name: Download AUTH test report artifact
        uses: actions/download-artifact@v3
        with:
          name: auth-api-test-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
