name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g jq-cli
      
      - name: Run Profile API Tests
        id: profile-tests
        run: |
          # Run Profile tests and capture the request body
          REQUEST_BODY=$(newman run Profile.postman_collection.json \
            -e DEV.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export profile-test-report.html \
            --export-environment updated-profile-env.json \
            --env-var 'extracted_email={{$randomEmail}}' \
            --env-var 'extracted_passcode=123456')
          
          # Extract email and passcode from the original request
          EMAIL=$(echo '$REQUEST_BODY' | jq -r '.email')
          PASSCODE=$(echo '$REQUEST_BODY' | jq -r '.passcode')
          
          echo "EMAIL=$EMAIL" >> $GITHUB_ENV
          echo "PASSCODE=$PASSCODE" >> $GITHUB_ENV
      
      - name: Prepare AUTH Environment
        run: |
          # Create a new environment file for AUTH tests
          jq --arg email "$EMAIL" --arg passcode "$PASSCODE" \
            '.values += [
              {"key": "email", "value": $email},
              {"key": "passcode", "value": $passcode}
            ]' DEV.postman_environment.json > updated-auth-env.json
      
      - name: Run AUTH API Tests
        run: |
          newman run AUTH.postman_collection.json \
            -e updated-auth-env.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export auth-test-report.html
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: api-test-reports
          path: |
            profile-test-report.html
            auth-test-report.html
