name: API Test and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Profile API tests with Newman
        id: profile-tests
        run: |
          newman run Profile.postman_collection.json \
            -e DEV.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export profile-test-report.html \
            --export-environment updated-env.json
          
          # Extract and log the credentials for verification
          echo "Generated email: $(jq -r '.values[] | select(.key=="email") | .value' updated-env.json)"
          echo "Generated passcode: $(jq -r '.values[] | select(.key=="passcode") | .value' updated-env.json)"

      - name: Run AUTH API tests with Newman
        if: success()
        run: |
          newman run AUTH.postman_collection.json \
            -e updated-env.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export auth-test-report.html

      - name: Upload Profile test report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: profile-api-test-report
          path: profile-test-report.html

      - name: Upload AUTH test report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: auth-api-test-report
          path: auth-test-report.html

  deploy-report:
    needs: run-api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Profile test report artifact
        uses: actions/download-artifact@v3
        with:
          name: profile-api-test-report

      - name: Download AUTH test report artifact
        uses: actions/download-artifact@v3
        with:
          name: auth-api-test-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
